<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\SubscribeController;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

// Welcome page route
Route::get('/', function () {
    return view('welcome');
});


// Authentication routes generated by Laravel
Auth::routes();

// Home route, accessible only for authenticated users
Route::get('/home', [HomeController::class, 'index'])->name('home');

// Subscribe routes, grouped under a prefix and protected by the 'auth' middleware
Route::prefix('subscribe')->middleware('auth')->group(function () {
    // Route for subscribing (POST request)
    Route::post('/{userId}', [SubscribeController::class, 'subscribe'])->name('subscribe.subscribe');

    // Route for unsubscribing (DELETE request)
    Route::delete('/{userId}', [SubscribeController::class, 'unsubscribe'])->name('subscribe.unsubscribe');
});
